package org.ageseries.libage.sim.electrical

import org.ageseries.libage.data.Quantity
import org.ageseries.libage.data.AMPERE
import org.ageseries.libage.data.COULOMB
import org.ageseries.libage.data.FARAD
import org.ageseries.libage.data.HENRY
import org.ageseries.libage.data.JOULE
import org.ageseries.libage.data.OHM
import org.ageseries.libage.data.VOLT
import org.ageseries.libage.data.WATT
import org.ageseries.libage.mathematics.approxEq
import org.ageseries.libage.mathematics.smoothstep
import org.ageseries.libage.sim.Pole
import kotlin.math.min
import kotlin.math.sign
import kotlin.math.sqrt

/**
 * Independent current source. Drives a current between the two nodes.
 * */
class CurrentSource : Port(), ReadoutElectricalComponent<CurrentSource, CurrentSource.Repository> {
    override val repositoryLayer = ElectricalReadoutRepositoryLayer<Repository> {
        Repository(this)
    }

    class Repository(val source: CurrentSource) : ReadoutRepository {
        var current = Quantity(0.0, AMPERE)
            private set

        var potential = Quantity(0.0, VOLT)
            private set

        var power = Quantity(0.0, WATT)
            private set

        override fun loadValues() {
            current = Quantity(source.current)
            potential = Quantity(source.potential)
            power = Quantity(source.power)
        }
    }

    override fun stamp() {
        simulation.system.stampCurrentKnown(
            positive.node,
            negative.node,
            current
        )
    }

    /**
     * Sets the current of the source. This is cheap to do, so consider using it in dynamic processes.
     * */
    var current: Double = 0.0
        set(value) {
            // Accept any, except NaN and infinity

            if(field != value) {
                if(value.isNaN() || value.isInfinite()) {
                    error("Invalid current $value!")
                }

                if(isStamped) {
                    simulation.system.changeCurrentKnown(
                        positive.node,
                        negative.node,
                        field,
                        value
                    )
                }

                field = value
            }
        }

    /**
     * Gets the power generated by this source. By Grissess' convention, this is positive when power is leaving the source.
     * */
    val power get() = potential * current
}

/**
 * Independent potential source. Creates the potential across the two nodes.
 * It introduces an equation into the system.
 * The backend calculates the current driving this potential.
 * */
class PotentialSource : Port(), ReadoutElectricalComponent<PotentialSource, PotentialSource.Repository> {
    override val repositoryLayer = ElectricalReadoutRepositoryLayer<Repository> {
        Repository(this)
    }

    class Repository(val source: PotentialSource) : ReadoutRepository {
        var potential = Quantity(0.0, VOLT)
            private set

        var current = Quantity(0.0, AMPERE)
            private set

        var power = Quantity(0.0, WATT)
            private set

        override fun loadValues() {
            potential = Quantity(source.potential)
            current = Quantity(source.current)
            power = Quantity(source.power)
        }
    }

    /**
     * Gets the unique potential source index.
     * This is used as an index into the linear system.
     * */
    var potentialIndex = -1 // Could be an alternative to the ID generator
        private set

    internal fun setPotentialIndex(index: Int) {
        check(potentialIndex == -1) {
            "Tried to set potential source index, but previous simulation wasn't destroyed!"
        }

        potentialIndex = index
    }

    override fun simulationDestroyed() {
        super.simulationDestroyed()

        potentialIndex = -1
    }

    /**
     * Stamps the *one-time* potential structure into the matrix, as well as the known.
     * */
    override fun stamp() {
        simulation.system.stampVoltageStructure(
            potentialIndex,
            positive.node,
            negative.node
        )

        simulation.system.stampVoltageKnown(
            potentialIndex,
            potential
        )
    }

    /**
     * Sets the potential of the source. This is cheap to do, so consider using it in dynamic processes.
     * */
    override var potential: Double = 0.0
        set(value) {
            // Accept any, except NaN and infinity

            if(field != value) {
                if(value.isNaN() || value.isInfinite()) {
                    error("Invalid potential $value!")
                }

                if(isStamped) {
                    simulation.system.changeVoltageKnown(
                        potentialIndex,
                        field,
                        value
                    )
                }

                field = value
            }
        }

    /**
     * Gets the current calculated by the solver. By Grissess' convention, this is positive when current is leaving the source.
     * */
    var current = 0.0
        internal set

    /**
     * Gets the power generated by this source. By Grissess' convention, this is positive when power is leaving the source.
     * */
    val power get() = potential * current
}

/**
 * Linear resistor. It contributes a conductance between two nodes in the system.
 * **Updating its resistance is expensive and forbidden for dynamic processes.**
 * _Updating resistance is fine for creating low-frequency switches._
 *
 * **Keep in mind that, if you extend this class, your device might get optimized into a [ResistorSystem] and not show up in [ElectricalSimulation.components].**
 * */
open class Resistor : Port(), ReadoutElectricalComponent<Resistor, Resistor.Repository> {
    override val repositoryLayer = ElectricalReadoutRepositoryLayer<Repository> {
        Repository(this)
    }

    class Repository(val resistor: Resistor) : ReadoutRepository {
        var resistance = Quantity(0.0, OHM)
            private set

        var potential = Quantity(0.0, VOLT)
            private set

        var current = Quantity(0.0, AMPERE)
            private set

        var power = Quantity(0.0, WATT)
            private set

        override fun loadValues() {
            resistance = Quantity(resistor.resistance)
            potential = Quantity(resistor.potential)
            current = Quantity(resistor.current)
            power = Quantity(resistor.power)
        }
    }

    /**
     * If the resistor gets optimized away by the [ElectricalCircuitCompiler.LineOptimizer], this field will be set on compilation.
     * */
    private var resistorSystemInternal: ResistorSystem? = null

    /**
     * Gets the optimized system.
     * Only legal to call if [isInOptimizedSystem] is true.
     * */
    val resistorSystem get() = if(resistorSystemInternal == null) error("Cannot get resistor system, not included in one!") else resistorSystemInternal!!
    val isInOptimizedSystem get() = resistorSystemInternal != null

    /**
     * Sets the optimized system.
     * This Resistor is no longer part of the system's matrix, so it will not stamp anything.
     * */
    internal fun setSystem(system: ResistorSystem) {
        check(resistorSystemInternal == null) {
            "Tried to set a resistor system, but the previous one wasn't destroyed!"
        }

        resistorSystemInternal = system
    }

    override fun simulationDestroyed() {
        super.simulationDestroyed()

        resistorSystemInternal = null
    }

    override fun stamp() {
        check(!isInOptimizedSystem)

        simulation.system.stampResistance(
            positive.node,
            negative.node,
            resistance
        )
    }

    /**
     * Sets the resistance. It must be a positive real number in the range [[ElectricalSimulation.MIN_RESISTANCE], [ElectricalSimulation.MAX_RESISTANCE]].
     * Setting a value outside that range, NaN or infinity will result in an error.
     * Changing resistance requires much computation, so it is advised to not do it very often or, ideally, keep resistance constant, and implement dynamic processes by varying sources.
     * */
    var resistance: Double = 1.0
        set(value) {
            // Accept positive, except NaN and infinity, very large values, and very small values:
            if(field != value) {
                if(value < 0.0) {
                    error("Invalid negative resistance $value!")
                }

                if(value.isNaN() || value.isInfinite()) {
                    error("Invalid resistance $value!")
                }

                if(value < ElectricalSimulation.MIN_RESISTANCE || value > ElectricalSimulation.MAX_RESISTANCE) {
                    error("Resistance $value is out of bounds [${ElectricalSimulation.MIN_RESISTANCE}, ${ElectricalSimulation.MAX_RESISTANCE}]!")
                }

                if(isInOptimizedSystem) {
                    resistorSystem.setChildChanged()
                }
                else if(isStamped) {
                    simulation.system.changeResistance(
                        positive.node,
                        negative.node,
                        field,
                        value
                    )
                }

                field = value
            }
        }

    /**
     * Updates the [resistance] if it's not within [eps] of [newResistance].
     * */
    fun updateResistance(newResistance: Double, eps: Double = 1e-5) : Boolean {
        if(resistance.approxEq(newResistance, eps)) {
            return false
        }

        resistance = newResistance
        return true
    }

    /**
     * Gets the current flowing through the device.
     * */
    val current: Double get() = potential / resistance

    /**
     * Gets the power dissipated by the resistor.
     * */
    val power: Double get() = current * potential
}

/**
 * Series resistors, optimized into one resistor.
 * For more information, see [ElectricalCircuitCompiler.LineOptimizer].
 * */
class ResistorSystem(graph: ElectricalCircuitCompiler.LineOptimizer.ProtoLineGraph, optimizer: ElectricalCircuitCompiler.LineOptimizer) : Port() {
    val resistors = graph.resistors.toTypedArray()

    /**
     * We will have N+1 virtual nodes.
     * The first and last are external nodes, and the `N - 1` rest of the nodes are internal.
     * */
    val virtualNodes: Array<ElectricalNode>

    /**
     * Re-writes the circuit data. See a summary of the process in [ElectricalCircuitCompiler.LineOptimizer].
     * */
    init {
        val internalNodeLookup = graph.internalNodes.toHashSet()

        /**
         * Removes the components from the simulation:
         * */
        graph.resistors.forEach {
            check(optimizer.circuitData.components.remove(it))
        }

        // Find external poles for each resistor:
        fun getExternalPole(edge: Resistor) : Pole {
            val nodeP = optimizer.nodesByPin[edge.positive]
            val nodeN = optimizer.nodesByPin[edge.negative]
            check(nodeP != null || nodeN != null)

            if(nodeP != null && nodeN != null) {
                if(internalNodeLookup.contains(nodeP)) {
                    return Pole.Negative
                }

                if(internalNodeLookup.contains(nodeN)) {
                    return Pole.Positive
                }

                error("Could not find external pole")
            }
            else if(nodeP != null) {
                check(internalNodeLookup.contains(nodeP))
                return Pole.Negative
            }
            else {
                check(internalNodeLookup.contains(nodeN))
                return Pole.Positive
            }
        }

        val externalPoleFirst = getExternalPole(graph.resistors.first())
        val externalPoleLast = getExternalPole(graph.resistors.last())

        /**
         * Goes into the external nodes, removes the edge resistor pins and adds the system's pins.
         * Creates a virtual node:
         * */
        fun remapEdgeAndCreateVNode(edge: Resistor, externalPole: Pole, systemPole: Pole) : ElectricalNode {
            // Find the pole of the resistor that goes to the outside:

            val externalPin = edge.getPin(externalPole)
            val externalNode = optimizer.nodesByPin[externalPin]
                ?: return ElectricalNode(ElectricalNode.VIRTUAL_ID, arrayOf(externalPin)) // Nothing to remap.

            val pinsInNode = optimizer.circuitData.forest[externalNode]

            if(ElectricalCircuitCompiler.USE_VALIDATION) {
                check(!graph.internalNodes.contains(externalNode))
                check(pinsInNode.contains(externalPin))
            }

            // Remove old pin:
            pinsInNode.remove(externalPin)

            val systemPin = getPin(systemPole)

            // Add system pin:
            pinsInNode.add(systemPin)

            // All done. The pin of the edge resistor has been removed from the circuit and replaced with ours.
            return  ElectricalNode(ElectricalNode.VIRTUAL_ID, arrayOf(externalPin))
        }

        // Choose system poles arbitrarily:

        val vP = remapEdgeAndCreateVNode(graph.resistors.first(), externalPoleFirst, Pole.Positive)
        val vN = remapEdgeAndCreateVNode(graph.resistors.last(), externalPoleLast, Pole.Negative)

        val virtualNodes = ArrayList<ElectricalNode>()
        virtualNodes.add(vP)

        /**
         * Deletes the internal nodes from the simulation and creates the virtual internal nodes:
         * */
        graph.internalNodes.forEach {
            val pins = optimizer.circuitData.forest.map.remove(it)
            check(pins != null)
            virtualNodes.add(ElectricalNode(ElectricalNode.VIRTUAL_ID, pins.toTypedArray()))
        }

        virtualNodes.add(vN)
        check(virtualNodes.size == graph.internalNodes.size + 2 && virtualNodes.size == graph.resistors.size + 1)

        /**
         * Creates the "virtual" nodes. We created a left and right virtual node, and then internal virtual nodes.
         * In total, we have `N + 1` virtual nodes, where `N` is the number of resistors.
         * */
        this.virtualNodes = virtualNodes.toTypedArray()

        /**
         * Sets the external virtual nodes for the resistors:
         * */
        graph.resistors.first().getPin(externalPoleFirst).setNode(virtualNodes.first())
        graph.resistors.last().getPin(externalPoleLast).setNode(virtualNodes.last())

        /**
         * Sets the internal virtual nodes for the resistors:
         * */
        for (i in 1 until virtualNodes.size - 1) {
            val internalNode = virtualNodes[i]
            check(internalNode.pins.size == 2)

            internalNode.pins.forEach { pin ->
                pin.setNode(internalNode)
            }
        }

        /**
         * Adds this system to the new components.
         * */
        optimizer.circuitData.components.add(this)

        /**
         * Sets the linear system:
         * */
        resistors.forEach {
            it.setSystem(this)
        }
    }

    /**
     * Stamps the [seriesResistance].
     * */
    override fun stamp() {
        simulation.system.stampResistance(
            positive.node,
            negative.node,
            seriesResistance
        )

        dirty = false
    }

    /**
     * If true, one of the [resistors] has changed its resistance.
     * The [seriesResistance] will be calculated and stamped on [prepareStep].
     * */
    var dirty = false
        private set

    /**
     * The series resistance of the system.
     * */
    var seriesResistance = resistors.sumOf { it.resistance }
        private set

    /**
     * Calculates the [seriesResistance] and stamps, if [dirty].
     * */
    override fun prepareStep() {
        /**
         * Applies steps for components extending the resistor.
         * */
        resistors.forEach {
            it.prepareStep()
        }

        if(!dirty) {
            return
        }

        dirty = false

        if(isStamped) {
            val newResistance = resistors.sumOf { it.resistance }

            if(newResistance != seriesResistance) {
                simulation.system.changeResistance(
                    positive.node,
                    negative.node,
                    seriesResistance,
                    newResistance
                )

                seriesResistance = newResistance
            }
        }
    }

    /**
     * Distributes results to the children.
     * This is done in the following manner:
     * - The system is a series of resistors, so the current through them is constant. This allows us to calculate the current through them using the [seriesResistance] and the system's potential drop.
     * - The first node in [virtualNodes] gets the potential of the [positive] node. This potential is also kept track of, as the *current* potential.
     * - Each resistor is traversed. The resistance causes a drop in the *current* potential. This drop is subtracted from the *current* potential, and the virtual node's potential is set to the *current* potential.
     * - At the end, the last virtual node's potential is ~equal to the potential of the [negative] node.
     * */
    override fun finishStep() {
        val current = potential / seriesResistance

        var currentPotential = positive.potential
        virtualNodes.first().potential = currentPotential

        resistors.forEachIndexed { index, resistor ->
            currentPotential -= current * resistor.resistance
            val node = virtualNodes[index + 1]
            node.potential = currentPotential
        }

        // The calculated potential drop should be ~equal to the actual potential drop, up to floating point error:
        check(currentPotential.approxEq(negative.potential, 1e-4))

        /**
         * Applies steps for components extending the resistor.
         * */
        resistors.forEach {
            it.finishStep()
        }
    }

    /**
     * Call when the resistance of the line needs to be updated.
     * It will be re-calculated in [prepareStep].
     * */
    fun setChildChanged() {
        dirty = true
    }
}

/**
 * An inductor implemented as a Norton system.
 * Uses *Backward Euler* integration.
 * */
class Inductor : NortonSystem(), ReadoutElectricalComponent<Inductor, Inductor.Repository> {
    override val repositoryLayer = ElectricalReadoutRepositoryLayer<Repository> {
        Repository(this)
    }

    class Repository(val inductor: Inductor) : ReadoutRepository {
        var inductance = Quantity(0.0, HENRY)
            private set

        var energy = Quantity(0.0, JOULE)
            private set

        var potential = Quantity(0.0, VOLT)
            private set

        var current = Quantity(0.0, AMPERE)
            private set

        override fun loadValues() {
            inductance = Quantity(inductor.inductance)
            energy = Quantity(inductor.energy)
            potential = Quantity(inductor.potential)
            current = Quantity(inductor.current)
        }
    }

    override fun getNortonResistance(value: Double) = value / simulation.dt

    /**
     * The inductance of the inductor.
     * Changing this is expensive!
     * */
    var inductance: Double
        get() = componentValue
        set(value) { componentValue = value }

    /**
     * The electromagnetic flux across the device.
     * */
    var flux = 0.0

    override fun prepareStep() {
        nortonCurrent = -flux / inductance
    }

    override fun finishStep() {
        flux += potential * simulation.dt
    }

    /**
     * Gets the energy stored in the electromagnetic field.
     * */
    val energy: Double get() = 0.5 * inductance * (current * current)
}

/**
 * A capacitor implemented as a Norton system.
 * Uses *Backward Euler* integration.
 * */
class Capacitor : NortonSystem(), ReadoutElectricalComponent<Capacitor, Capacitor.Repository> {
    override val repositoryLayer = ElectricalReadoutRepositoryLayer<Repository> {
        Repository(this)
    }

    class Repository(val capacitor: Capacitor) : ReadoutRepository {
        var capacitance = Quantity(0.0, FARAD)
            private set

        var charge = Quantity(0.0, COULOMB)
            private set

        var internalEnergy = Quantity(0.0, JOULE)
            private set

        var potential = Quantity(0.0, VOLT)
            private set

        var current = Quantity(0.0, AMPERE)
            private set

        override fun loadValues() {
            capacitance = Quantity(capacitor.capacitance)
            charge = Quantity(capacitor.charge)
            internalEnergy = Quantity(capacitor.internalEnergy)
            potential = Quantity(capacitor.potential)
            current = Quantity(capacitor.current)
        }
    }

    override fun getNortonResistance(value: Double) = simulation.dt / value

    /**
     * The capacitance of the capacitor.
     * Changing this is expensive!
     * */
    var capacitance: Double
        get() = componentValue
        set(value) { componentValue = value }

    /**
     * Potential across the device from the last timestep.
     * */
    var lastPotential: Double = 0.0

    /**
     * The last potential difference, calculated in [finishStep].
     * */
    var lastDv = 0.0

    /**
     * The amount of charge this capacitor has accumulated.
     */
    var charge: Double = 0.0

    override fun prepareStep() {
        nortonCurrent = charge / simulation.dt
        trickUsed = false
    }

    override fun finishStep() {
        val potential = potential

        val dv = potential - lastPotential
        val dq = capacitance * dv

        charge += dq
        lastPotential = potential
        lastDv = dv
    }

    /**
     * Removes energy from the capacitor.
     * @param requestedEnergy The upper bound on the energy to withdraw.
     * @return The actual energy that was removed.
     *
     * **P.S. If you want to use [lostEnergy], use it before calling this. This affects that result.
     */
    fun withdrawEnergy(requestedEnergy: Double): Double {
        require(requestedEnergy >= 0.0 && !requestedEnergy.isNaN() && !requestedEnergy.isInfinite()) {
            "Invalid requested energy $requestedEnergy!"
        }

        if (requestedEnergy <= 0.0 || capacitance <= 0.0) {
            return 0.0
        }

        val internalEnergy = this@Capacitor.internalEnergy
        val energyToRemove = min(requestedEnergy, internalEnergy)
        val newEnergy = internalEnergy - energyToRemove
        val newCharge = sign(charge) * sqrt(2.0 * capacitance * newEnergy)

        charge = newCharge

        val temp = lastPotential
        lastPotential = newCharge / capacitance
        lastDv = lastPotential - temp

        return energyToRemove
    }

    private var trickUsed = false

    /**
     * Removes energy from the capacitor, but first checks if the numeric losses of the model satisfy this request.
     * If not, it fills the rest of the request with [withdrawEnergy].
     * **Call this once per tick, at most!**
     *
     * Over time, using this instead of [withdrawEnergy] results in a more accurate energy balance.
     * Keep in mind that, if the [lostEnergy] is not wholly consumed this step, it will be gone next step.
     * */
    fun withdrawEnergyTrick(requestedEnergy: Double): Double {
        check(!trickUsed) {
            "Cannot use the energy trick more than once per tick!"
        }

        trickUsed = true

        val loss = lostEnergy

        if(requestedEnergy <= loss) {
            return requestedEnergy
        }

        return loss + withdrawEnergy(requestedEnergy - loss)
    }

    /**
     * Gets the energy stored based on the current [charge].
     * */
    val internalEnergy get() = 0.5 * charge * charge / capacitance

    /**
     * Energy lost in the numerical model this step.
     * */
    val lostEnergy get() = 0.5 * capacitance * (lastDv * lastDv)

    /**
     * Gets the total energy possible to withdraw with [withdrawEnergyTrick].
     * */
    val virtualEnergy get() = this@Capacitor.internalEnergy + lostEnergy
}

/**
 * A capacitor implemented as a Norton system.
 * Uses *Trapezoidal* integration (relatively stable, almost energy-conserving). It's more accurate than the [Capacitor], but less stable.
 * This capacitor doesn't damp high-frequency oscillations. It's stable, but can cause some ringing in the system.
 * A simple test case: Create a [PotentialSource] with `10V` connected to a [CapacitorTrapezoidal], and run it for two steps.
 * In the first step, the capacitor will fully charge, but the source will have dispatched more energy than was stored.
 * Next step, the capacitor will create a back-current that will create a negative power on the source, which when accounted for, will set the energy balance.
 * */
class CapacitorTrapezoidal : NortonSystem(), ReadoutElectricalComponent<CapacitorTrapezoidal, CapacitorTrapezoidal.Repository> {
    override val repositoryLayer = ElectricalReadoutRepositoryLayer<Repository> {
        Repository(this)
    }

    class Repository(val capacitor: CapacitorTrapezoidal) : ReadoutRepository {
        var capacitance = Quantity(0.0, FARAD)
            private set

        var charge = Quantity(0.0, COULOMB)
            private set

        var internalEnergy = Quantity(0.0, JOULE)
            private set

        var potential = Quantity(0.0, VOLT)
            private set

        var current = Quantity(0.0, AMPERE)
            private set

        override fun loadValues() {
            capacitance = Quantity(capacitor.capacitance)
            charge = Quantity(capacitor.charge)
            internalEnergy = Quantity(capacitor.internalEnergy)
            potential = Quantity(capacitor.potential)
            current = Quantity(capacitor.current)
        }
    }

    override fun getNortonResistance(value: Double) = simulation.dt / (2.0 * value)

    /**
     * The capacitance of the capacitor.
     * Changing this is expensive!
     * */
    var capacitance: Double
        get() = componentValue
        set(value) { componentValue = value }

    /**
     * Potential across the device from the last timestep.
     * */
    var lastPotential: Double = 0.0

    /**
     * The last capacitor current (for trapezoidal).
     * */
    var lastCapacitorCurrent: Double = 0.0

    /**
     * The last potential difference, calculated in [finishStep].
     * */
    var lastDv = 0.0

    /**
     * The amount of charge this capacitor has accumulated.
     */
    var charge: Double = 0.0

    override fun prepareStep() {
        nortonCurrent = nortonConductance * lastPotential + lastCapacitorCurrent
    }

    override fun finishStep() {
        val potential = potential

        val dv = potential - lastPotential
        val dq = capacitance * dv

        val previousEnergy = 0.5 * (charge * charge) / capacitance

        charge += dq

        lastPotential = potential
        lastCapacitorCurrent = capacitance * dv / simulation.dt
        lastDv = dv

        // Approximates work done by the external circuit. This allows us to calculate an energy error:
        lostEnergy = potential * current * simulation.dt - (internalEnergy - previousEnergy)
    }

    /**
     * Removes energy from the capacitor.
     * @param requestedEnergy The upper bound on the energy to withdraw.
     * @return The actual energy that was removed.
     */
    fun withdrawEnergy(requestedEnergy: Double): Double {
        require(requestedEnergy >= 0.0 && !requestedEnergy.isNaN() && !requestedEnergy.isInfinite()) {
            "Invalid requested energy $requestedEnergy!"
        }

        if (requestedEnergy <= 0.0 || capacitance <= 0.0) {
            return 0.0
        }

        val internalEnergy = internalEnergy
        val energyToRemove = min(requestedEnergy, internalEnergy)
        val newEnergy = internalEnergy - energyToRemove
        val newCharge = sign(charge) * sqrt(2.0 * capacitance * newEnergy)

        val dq = newCharge - charge
        charge = newCharge

        val temp = lastPotential
        lastPotential = newCharge / capacitance
        lastDv = lastPotential - temp

        lastCapacitorCurrent = -dq / simulation.dt

        return energyToRemove
    }

    /**
     * Removes energy from the capacitor, but first checks if the numeric losses of the model satisfy this request.
     * If not, it fills the rest of the request with [withdrawEnergy].
     * This mutates [lostEnergy]!
     *
     * Over time, using this instead of [withdrawEnergy] results in a more accurate energy balance.
     * Keep in mind that, if the [lostEnergy] is not wholly consumed this step, it will be gone next step.
     * */
    fun withdrawEnergyTrick(requestedEnergy: Double): Double {
        val loss = lostEnergy

        if(loss <= 0.0) {
            // Pushback from the integration.
            return withdrawEnergy(requestedEnergy)
        }

        if(requestedEnergy <= loss) {
            lostEnergy -= requestedEnergy
            return requestedEnergy
        }

        lostEnergy = 0.0
        return loss + withdrawEnergy(requestedEnergy - loss)
    }

    /**
     * Gets the energy stored based on the current [charge].
     * */
    val internalEnergy get() = 0.5 * charge * charge / capacitance

    /**
     * Energy lost in the numerical model this step.
     * **Can be negative if the model rung!**
     * */
    var lostEnergy = 0.0
        private set

    /**
     * Gets the total energy possible to withdraw with [withdrawEnergyTrick].
     * */
    val virtualEnergy get() = internalEnergy + lostEnergy.coerceAtLeast(0.0)
}

/**
 * Diode implemented as a potential-controlled switch, at `V = 0`. Uses hysteresis to harden against oscillations.
 * This is the cheapest possible way to implement something **like** a diode.
 * It doesn't simulate a semiconductor so no nonlinear behavior can be extracted from this, to formulate other simulations (e.g. the solar panel simulation).
 * All that must be simulated with a model (for example, a [PotentialSource] in series with a [LinearDiode], where the source potential is modulated).
 * */
class LinearDiode : Resistor() {
    /**
     * If true, the diode is in its conducting state.
     * */
    var isConducting: Boolean

    /**
     * Hysteresis voltage to reduce oscillations.
     * Explanation: The state won't switch if only the potential's sign switched.
     * We check if the potential changed more than [hysteresisVoltage] above or below `0`. Only then, we apply the switch.
     */
    var hysteresisVoltage: Double = 0.01

    /**
     * The resistance in forward bias (that is, when the potential is positive).
     * */
    var forwardResistance: Double = 0.01
        set(value) {
            if (value < ElectricalSimulation.MIN_RESISTANCE || value > ElectricalSimulation.MAX_RESISTANCE || value.isNaN() || value.isInfinite()) {
                error("Invalid forward resistance $value!")
            }

            field = value

            if(isConducting) {
                resistance = value
            }
        }

    /**
     * The resistance in reverse bias (that is, when the potential is negative).
     */
    var reverseResistance: Double = 1000.0
        set(value) {
            if (value < ElectricalSimulation.MIN_RESISTANCE || value > ElectricalSimulation.MAX_RESISTANCE || value.isNaN() || value.isInfinite()) {
                error("Invalid reverse resistance $value!")
            }

            field = value

            if(!isConducting) {
                resistance = value
            }
        }

    /**
     * Sets the diode as initially open.
     * */
    init {
        isConducting = false
        resistance = reverseResistance
    }

    /**
     * Switches the resistance, with hysteresis to make it more resistant to oscillations.
     * */
    override fun prepareStep() {
        val potential = potential

        /**
         * Conductance based on the ideal behavior:
         * */
        val isInPositiveRegion = potential > 0.0

        /**
         * Apply hysteresis:
         * */
        val targetState = if (isInPositiveRegion != isConducting) {
            if (isInPositiveRegion) {
                potential > hysteresisVoltage
            } else {
                potential < -hysteresisVoltage
            }
        }
        else {
            // No state change:
            isConducting
        }

        /**
         * Update resistance if needed:
         * */
        if (targetState != isConducting) {
            isConducting = targetState

            resistance = if (targetState) {
                forwardResistance
            }
            else {
                reverseResistance
            }
        }
    }
}

/**
 * A Power-Controlled source.
 * These are difficult to implement *without spending a lot of CPU time* (they are nonlinear and stiff, and they don't usually play well with each other).
 * As such, approximations were made. What I did is (much) more expensive than what 「Grissess」 did, but I really hope it pays off (I would be surprised if it did...).
 *
 * See [ElectricalSimulation] for more information about how it was implemented.
 *
 * It is recommended to use these devices **only when necessary**. If possible, use [PotentialSource]s instead.
 * */
class PowerSource : NortonSystem(), ReadoutElectricalComponent<PowerSource, PowerSource.Repository> {
    override val repositoryLayer = ElectricalReadoutRepositoryLayer<Repository> {
        Repository(this)
    }

    class Repository(val source: PowerSource) : ReadoutRepository {
        var maxPotential = Quantity(0.0, VOLT)
            private set

        var maxPower = Quantity(0.0, WATT)
            private set

        var potential = Quantity(0.0, VOLT)
            private set

        var current = Quantity(0.0, AMPERE)
            private set

        var power = Quantity(0.0, WATT)
            private set

        override fun loadValues() {
            maxPotential = Quantity(source.maxPotential)
            maxPower = Quantity(source.maxPower)
            potential = Quantity(source.potential)
            current = Quantity(source.current)
            power = Quantity(source.power)
        }
    }

    var powerSourceIndex = -1
        private set

    /**
     * Sets the device's nonlinear solver index.
     * */
    internal fun setPowerSourceIndex(index: Int) {
        check(powerSourceIndex == -1) {
            "Tried to set power source index, but previous simulation wasn't destroyed!"
        }

        powerSourceIndex = index
    }

    override fun simulationDestroyed() {
        super.simulationDestroyed()

        powerSourceIndex = -1
    }

    /**
     * The "potential rating" of the device. This will also be the potential constraint.
     * It's part of the conductance stabilizing the Norton system. It must be positive and non-zero normally.
     * **Changing this causes a matrix re-factor unless [freezeResistance] is set.**
     * */
    var maxPotential: Double = 1.0
        set(value) {
            if(value.isNaN() || value.isInfinite() || value < 0.0) {
                error("Invalid max potential $value")
            }

            field = value

            if(!freezeResistance) {
                computePVCharacteristicResistance()
            }
        }

    /**
     * The "power rating" of the device. This constrains the [targetPower] in a range of [0, [maxPower]].
     * It's part of the conductance stabilizing the Norton system. It must be positive and non-zero normally.
     * **Changing this causes a matrix re-factor unless [freezeResistance] is set.**
     * */
    var maxPower: Double = 1.0
        set(value) {
            if(value.isNaN() || value.isInfinite() || value <= 0.0) {
                error("Invalid max power $value")
            }

            field = value

            if(!freezeResistance) {
                computePVCharacteristicResistance()
            }
        }

    /**
     * Blend region used to interpolate the piecewise function that appears in the residual calculation.
     * */
    var blendRegion = 0.95

    /**
     * The power to generate.
     * */
    var targetPower = 0.0

    /**
     * If set to true, then the characteristic resistance will not be re-computed when [maxPotential] or [maxPower] is changed.
     *
     * If the operating regime of this source is variable (dynamic), consider initializing [maxPotential] and [maxPower] to some reasonable operating point estimates or manually setting [characteristicResistance], then freezing.
     * */
    var freezeResistance = false

    /**
     * Computes *some* resistance for the Norton system.
     * This resistance is a characteristic resistance, that sort of plays well.
     * */
    fun computePVCharacteristicResistance() {
        characteristicResistance = if(maxPower.approxEq(0.0) || maxPotential.approxEq(0.0)) {
            ElectricalSimulation.MAX_RESISTANCE
        } else {
            (maxPotential * maxPotential / maxPower).coerceIn(ElectricalSimulation.MIN_RESISTANCE, ElectricalSimulation.MAX_RESISTANCE)
        }
    }

    init {
        computePVCharacteristicResistance()
    }

    /**
     * The stabilizing resistance of the Norton system.
     * */
    var characteristicResistance: Double
        get() = componentValue
        set(value) { componentValue = value }

    /**
     * Called by the nonlinear solver to set a new current.
     * This will be used to re-solve the circuit to get the new power, and new residual.
     * */
    internal fun setCurrentFromSolver(current: Double) {
        nortonCurrent = current
    }

    /**
     * Gets the power generated by this source. By Grissess' convention, this is positive when power is leaving the source.
     * */
    val power get() = -potential * current
}