package org.ageseries.libage.sim.electrical

import org.ageseries.libage.data.*
import org.ageseries.libage.mathematics.approxEq
import kotlin.math.abs
import kotlin.math.min
import kotlin.math.sign
import kotlin.math.sqrt

/**
 * Independent current source. Drives a current between the two nodes.
 * */
class CurrentSource : Port(), ReadoutElectricalComponent<CurrentSource, CurrentSource.Repository> {
    override val repositoryLayer = ElectricalReadoutRepositoryLayer<Repository> {
        Repository(this)
    }

    class Repository(val source: CurrentSource) : ReadoutRepository {
        var current = Quantity(0.0, AMPERE)
            private set

        var potential = Quantity(0.0, VOLT)
            private set

        var power = Quantity(0.0, WATT)
            private set

        override fun loadValues() {
            current = Quantity(source.current)
            potential = Quantity(source.potential)
            power = Quantity(source.power)
        }
    }

    override fun stamp() {
        simulation.system.stampCurrentKnown(
            positive.node,
            negative.node,
            current
        )
    }

    /**
     * Sets the current of the source. This is cheap to do, so consider using it in dynamic processes.
     * */
    var current: Double = 0.0
        set(value) {
            // Accept any, except NaN and infinity

            if(field != value) {
                if(value.isNaN() || value.isInfinite()) {
                    error("Invalid current $value!")
                }

                if(isStamped) {
                    simulation.system.changeCurrentKnown(
                        positive.node,
                        negative.node,
                        field,
                        value
                    )
                }

                field = value
            }
        }

    /**
     * Gets the power generated by this source. By Grissess' convention, this is positive when power is leaving the source.
     * */
    val power get() = potential * current
}

/**
 * Independent potential source. Creates the potential across the two nodes.
 * It introduces an equation into the system.
 * The backend calculates the current driving this potential.
 * */
class PotentialSource : Port(), ReadoutElectricalComponent<PotentialSource, PotentialSource.Repository> {
    override val repositoryLayer = ElectricalReadoutRepositoryLayer<Repository> {
        Repository(this)
    }

    class Repository(val source: PotentialSource) : ReadoutRepository {
        var potential = Quantity(0.0, VOLT)
            private set

        var current = Quantity(0.0, AMPERE)
            private set

        var power = Quantity(0.0, WATT)
            private set

        override fun loadValues() {
            potential = Quantity(source.potential)
            current = Quantity(source.current)
            power = Quantity(source.power)
        }
    }

    /**
     * Gets the unique potential source index.
     * This is used as an index into the linear system.
     * */
    var potentialIndex = -1 // Could be an alternative to the ID generator
        private set

    internal fun setPotentialIndex(index: Int) {
        check(potentialIndex == -1) {
            "Tried to set potential source index, but previous simulation wasn't destroyed!"
        }

        potentialIndex = index
    }

    override fun simulationDestroyed() {
        super.simulationDestroyed()

        potentialIndex = -1
    }

    /**
     * Stamps the *one-time* potential structure into the matrix, as well as the known.
     * */
    override fun stamp() {
        simulation.system.stampVoltageStructure(
            potentialIndex,
            positive.node,
            negative.node
        )

        simulation.system.stampVoltageKnown(
            potentialIndex,
            potential
        )
    }

    /**
     * Sets the potential of the source. This is cheap to do, so consider using it in dynamic processes.
     * */
    override var potential: Double = 0.0
        set(value) {
            // Accept any, except NaN and infinity

            if(field != value) {
                if(value.isNaN() || value.isInfinite()) {
                    error("Invalid potential $value!")
                }

                if(isStamped) {
                    simulation.system.changeVoltageKnown(
                        potentialIndex,
                        field,
                        value
                    )
                }

                field = value
            }
        }

    /**
     * Gets the current calculated by the solver. By Grissess' convention, this is positive when current is leaving the source.
     * */
    var current = 0.0
        internal set

    /**
     * Gets the power generated by this source. By Grissess' convention, this is positive when power is leaving the source.
     * */
    val power get() = potential * current
}

/**
 * Linear resistor. It contributes a conductance between two nodes in the system.
 * **Updating its resistance is expensive and forbidden for dynamic processes.**
 * _Updating resistance is fine for creating low-frequency switches._
 *
 * **Keep in mind that, if you extend this class, your device might get optimized into a [ResistorSystem] and not show up in [ElectricalSimulation.components].**
 * */
open class Resistor : Port(), ReadoutElectricalComponent<Resistor, Resistor.Repository> {
    override val repositoryLayer = ElectricalReadoutRepositoryLayer<Repository> {
        Repository(this)
    }

    class Repository(val resistor: Resistor) : ReadoutRepository {
        var resistance = Quantity(0.0, OHM)
            private set

        var potential = Quantity(0.0, VOLT)
            private set

        var current = Quantity(0.0, AMPERE)
            private set

        var power = Quantity(0.0, WATT)
            private set

        override fun loadValues() {
            resistance = Quantity(resistor.resistance)
            potential = Quantity(resistor.potential)
            current = Quantity(resistor.current)
            power = Quantity(resistor.power)
        }
    }

    /**
     * If the resistor gets optimized away by the [ElectricalCircuitCompiler.LineOptimizer], this field will be set on compilation.
     * */
    private var resistorSystemInternal: ResistorSystem? = null

    /**
     * Gets the optimized system.
     * Only legal to call if [isInOptimizedSystem] is true.
     * */
    val resistorSystem get() = if(resistorSystemInternal == null) error("Cannot get resistor system, not included in one!") else resistorSystemInternal!!
    val isInOptimizedSystem get() = resistorSystemInternal != null

    /**
     * Sets the optimized system.
     * This Resistor is no longer part of the system's matrix, so it will not stamp anything.
     * */
    internal fun setSystem(system: ResistorSystem) {
        check(resistorSystemInternal == null) {
            "Tried to set a resistor system, but the previous one wasn't destroyed!"
        }

        resistorSystemInternal = system
    }

    override fun simulationDestroyed() {
        super.simulationDestroyed()

        resistorSystemInternal = null
    }

    override fun stamp() {
        check(!isInOptimizedSystem)

        simulation.system.stampResistance(
            positive.node,
            negative.node,
            resistance
        )
    }

    /**
     * Sets the resistance. It must be a positive real number in the range [[ElectricalSimulation.MIN_RESISTANCE], [ElectricalSimulation.MAX_RESISTANCE]].
     * Setting a value outside that range, NaN or infinity will result in an error.
     * Changing resistance requires much computation, so it is advised to not do it very often or, ideally, keep resistance constant, and implement dynamic processes by varying sources.
     * */
    var resistance: Double = 1.0
        set(value) {
            // Accept positive, except NaN and infinity, very large values, and very small values:
            if(field != value) {
                if(value < 0.0) {
                    error("Invalid negative resistance $value!")
                }

                if(value.isNaN() || value.isInfinite()) {
                    error("Invalid resistance $value!")
                }

                if(value < ElectricalSimulation.MIN_RESISTANCE || value > ElectricalSimulation.MAX_RESISTANCE) {
                    error("Resistance $value is out of bounds [${ElectricalSimulation.MIN_RESISTANCE}, ${ElectricalSimulation.MAX_RESISTANCE}]!")
                }

                if(isInOptimizedSystem) {
                    resistorSystem.setChildChanged()
                }
                else if(isStamped) {
                    simulation.system.changeResistance(
                        positive.node,
                        negative.node,
                        field,
                        value
                    )
                }

                field = value
            }
        }

    /**
     * Updates the [resistance] if it's not within [eps] of [newResistance].
     * */
    fun updateResistance(newResistance: Double, eps: Double = 1e-5) : Boolean {
        if(resistance.approxEq(newResistance, eps)) {
            return false
        }

        resistance = newResistance
        return true
    }

    /**
     * Gets the current flowing through the device.
     * */
    val current: Double get() = potential / resistance

    /**
     * Gets the power dissipated by the resistor.
     * */
    val power: Double get() = current * potential
}

/**
 * Series resistors, optimized into one resistor.
 * For more information, see [ElectricalCircuitCompiler.LineOptimizer].
 * */
class ResistorSystem(graph: ElectricalCircuitCompiler.LineOptimizer.ProtoLineGraph, optimizer: ElectricalCircuitCompiler.LineOptimizer) : Port() {
    val resistors = graph.resistors.toTypedArray()

    /**
     * We will have N+1 virtual nodes.
     * The first and last are external nodes, and the `N - 1` rest of the nodes are internal.
     * */
    val virtualNodes: Array<ElectricalNode>

    /**
     * Re-writes the circuit data. See a summary of the process in [ElectricalCircuitCompiler.LineOptimizer].
     * */
    init {
        val internalNodeLookup = graph.internalNodes.toHashSet()

        /**
         * Removes the components from the simulation:
         * */
        graph.resistors.forEach {
            check(optimizer.circuitData.components.remove(it))
        }

        // Find external poles for each resistor:
        fun getExternalPole(edge: Resistor) : Pole {
            val nodeP = optimizer.nodesByPin[edge.positive]
            val nodeN = optimizer.nodesByPin[edge.negative]
            check(nodeP != null || nodeN != null)

            if(nodeP != null && nodeN != null) {
                if(internalNodeLookup.contains(nodeP)) {
                    return Pole.Negative
                }

                if(internalNodeLookup.contains(nodeN)) {
                    return Pole.Positive
                }

                error("Could not find external pole")
            }
            else if(nodeP != null) {
                check(internalNodeLookup.contains(nodeP))
                return Pole.Negative
            }
            else {
                check(internalNodeLookup.contains(nodeN))
                return Pole.Positive
            }
        }

        val externalPoleFirst = getExternalPole(graph.resistors.first())
        val externalPoleLast = getExternalPole(graph.resistors.last())

        /**
         * Goes into the external nodes, removes the edge resistor pins and adds the system's pins.
         * Creates a virtual node:
         * */
        fun remapEdgeAndCreateVNode(edge: Resistor, externalPole: Pole, systemPole: Pole) : ElectricalNode {
            // Find the pole of the resistor that goes to the outside:

            val externalPin = edge.getPin(externalPole)
            val externalNode = optimizer.nodesByPin[externalPin]
                ?: return ElectricalNode(ElectricalNode.VIRTUAL_ID, arrayOf(externalPin)) // Nothing to remap.

            val pinsInNode = optimizer.circuitData.forest[externalNode]

            if(ElectricalCircuitCompiler.USE_VALIDATION) {
                check(!graph.internalNodes.contains(externalNode))
                check(pinsInNode.contains(externalPin))
            }

            // Remove old pin:
            pinsInNode.remove(externalPin)

            val systemPin = getPin(systemPole)

            // Add system pin:
            pinsInNode.add(systemPin)

            // All done. The pin of the edge resistor has been removed from the circuit and replaced with ours.
            return  ElectricalNode(ElectricalNode.VIRTUAL_ID, arrayOf(externalPin))
        }

        // Choose system poles arbitrarily:

        val vP = remapEdgeAndCreateVNode(graph.resistors.first(), externalPoleFirst, Pole.Positive)
        val vN = remapEdgeAndCreateVNode(graph.resistors.last(), externalPoleLast, Pole.Negative)

        val virtualNodes = ArrayList<ElectricalNode>()
        virtualNodes.add(vP)

        /**
         * Deletes the internal nodes from the simulation and creates the virtual internal nodes:
         * */
        graph.internalNodes.forEach {
            val pins = optimizer.circuitData.forest.map.remove(it)
            check(pins != null)
            virtualNodes.add(ElectricalNode(ElectricalNode.VIRTUAL_ID, pins.toTypedArray()))
        }

        virtualNodes.add(vN)
        check(virtualNodes.size == graph.internalNodes.size + 2 && virtualNodes.size == graph.resistors.size + 1)

        /**
         * Creates the "virtual" nodes. We created a left and right virtual node, and then internal virtual nodes.
         * In total, we have `N + 1` virtual nodes, where `N` is the number of resistors.
         * */
        this.virtualNodes = virtualNodes.toTypedArray()

        /**
         * Sets the external virtual nodes for the resistors:
         * */
        graph.resistors.first().getPin(externalPoleFirst).setNode(virtualNodes.first())
        graph.resistors.last().getPin(externalPoleLast).setNode(virtualNodes.last())

        /**
         * Sets the internal virtual nodes for the resistors:
         * */
        for (i in 1 until virtualNodes.size - 1) {
            val internalNode = virtualNodes[i]
            check(internalNode.pins.size == 2)

            internalNode.pins.forEach { pin ->
                pin.setNode(internalNode)
            }
        }

        /**
         * Adds this system to the new components.
         * */
        optimizer.circuitData.components.add(this)

        /**
         * Sets the linear system:
         * */
        resistors.forEach {
            it.setSystem(this)
        }

        /**
         * Loads their presentation (for normal components, it's done in the simulation's constructor):
         * */
        resistors.forEach {
            it.repositoryLayer.loadPresentation()
        }
    }

    /**
     * Sets the simulation for the resistors.
     * */
    override fun setSimulation(simulation: ElectricalSimulation) {
        super.setSimulation(simulation)

        resistors.forEach {
            it.setSimulation(simulation)
        }
    }

    /**
     * Stamps the [seriesResistance].
     * */
    override fun stamp() {
        if(dirty) {
            seriesResistance = resistors.sumOf { it.resistance }
            dirty = false
        }

        simulation.system.stampResistance(
            positive.node,
            negative.node,
            seriesResistance
        )
    }

    /**
     * If true, one of the [resistors] has changed its resistance.
     * The [seriesResistance] will be calculated and stamped on [prepareStep].
     * */
    var dirty = false
        private set

    /**
     * The series resistance of the system.
     * It can be outside the range specified in [ElectricalSimulation], but I think that is fine (we set the orders of those values to be ~acceptable).
     * Issues would only occur if tens of max resistance resistors were in series.
     * */
    var seriesResistance = resistors.sumOf { it.resistance }
        private set

    /**
     * Calculates the [seriesResistance] and stamps, if [dirty].
     * Also propagates [prepareStep].
     * */
    override fun prepareStep() {
        resistors.forEach {
            it.prepareStep() // e.g. Diodes
        }

        if(!dirty) {
            return
        }

        dirty = false

        val newResistance = resistors.sumOf { it.resistance }

        if(isStamped) {
            if(newResistance != seriesResistance) {
                simulation.system.changeResistance(
                    positive.node,
                    negative.node,
                    seriesResistance,
                    newResistance
                )
            }
        }

        seriesResistance = newResistance
    }

    /**
     * Distributes results to the children. Also propagates [finishStep].
     * This is done in the following manner:
     * - The system is a series of resistors, so the current through them is constant. This allows us to calculate the current through them using the [seriesResistance] and the system's potential drop.
     * - The first node in [virtualNodes] gets the potential of the [positive] node. This potential is also kept track of, as the *current* potential.
     * - Each resistor is traversed. The resistance causes a drop in the *current* potential. This drop is subtracted from the *current* potential, and the virtual node's potential is set to the *current* potential.
     * - At the end, the last virtual node's potential is ~equal to the potential of the [negative] node.
     *
     * *If any of the pins is floating, the results are all `0`.*
     * */
    override fun finishStep() {
        val p = positive.potential
        val n = negative.potential

        val current = (p - n) / seriesResistance

        var potentialAtNode = p
        virtualNodes.first().potential = potentialAtNode

        resistors.forEachIndexed { index, resistor ->
            potentialAtNode -= current * resistor.resistance
            val node = virtualNodes[index + 1]
            node.potential = potentialAtNode
        }

        // The calculated potential drop should be ~equal to the actual potential drop, up to floating point error:
        check(potentialAtNode.approxEq(n, 1e-4 /* Very generous */)) {
            "Resistor System condition wasn't satisfied: expected potential of $n, got $potentialAtNode"
        }
        /**
         * After we set their new states, we can finish the step.
         * */
        resistors.forEach {
            it.finishStep()
        }

        /**
         * Also updates their presentation:
         * */
        resistors.forEach {
            it.repositoryLayer.loadAndSwap()
        }
    }

    /**
     * Call when the resistance of the line needs to be updated.
     * It will be re-calculated in [prepareStep].
     * */
    fun setChildChanged() {
        dirty = true
    }

    /**
     * Clears the virtual nodes from the resistors.
     * */
    override fun simulationDestroyed() {
        super.simulationDestroyed()

        resistors.forEach {
            it.simulationDestroyed()
        }
    }
}

/**
 * An inductor implemented as a Norton system.
 * Uses *Backward Euler* integration.
 * */
class Inductor : NortonSystem(), ReadoutElectricalComponent<Inductor, Inductor.Repository> {
    override val repositoryLayer = ElectricalReadoutRepositoryLayer<Repository> {
        Repository(this)
    }

    class Repository(val inductor: Inductor) : ReadoutRepository {
        var inductance = Quantity(0.0, HENRY)
            private set

        var energy = Quantity(0.0, JOULE)
            private set

        var potential = Quantity(0.0, VOLT)
            private set

        var current = Quantity(0.0, AMPERE)
            private set

        override fun loadValues() {
            inductance = Quantity(inductor.inductance)
            energy = Quantity(inductor.energy)
            potential = Quantity(inductor.potential)
            current = Quantity(inductor.current)
        }
    }

    override fun getNortonResistance(value: Double) = value / simulation.dt

    /**
     * The inductance of the inductor.
     * Changing this is expensive!
     * */
    var inductance: Double
        get() = componentValue
        set(value) { componentValue = value }

    /**
     * The electromagnetic flux across the device.
     * */
    var flux = 0.0

    override fun prepareStep() {
        nortonCurrent = -flux / inductance
    }

    override fun finishStep() {
        flux += potential * simulation.dt
    }

    /**
     * Gets the energy stored in the electromagnetic field.
     * */
    val energy: Double get() = 0.5 * inductance * (current * current)

    val power get() = potential * current
}

/**
 * A capacitor implemented as a Norton system.
 * Uses *Backward Euler* integration.
 * */
class Capacitor : NortonSystem(), ReadoutElectricalComponent<Capacitor, Capacitor.Repository> {
    companion object {
        private const val CONSISTENCY_TOLERANCE = 1e-10
    }

    override val repositoryLayer = ElectricalReadoutRepositoryLayer<Repository> {
        Repository(this)
    }

    class Repository(val capacitor: Capacitor) : ReadoutRepository {
        var capacitance = Quantity(0.0, FARAD)
            private set

        var charge = Quantity(0.0, COULOMB)
            private set

        var internalEnergy = Quantity(0.0, JOULE)
            private set

        var potential = Quantity(0.0, VOLT)
            private set

        var current = Quantity(0.0, AMPERE)
            private set

        override fun loadValues() {
            capacitance = Quantity(capacitor.capacitance)
            charge = Quantity(capacitor.charge)
            internalEnergy = Quantity(capacitor.internalEnergy)
            potential = Quantity(capacitor.potential)
            current = Quantity(capacitor.current)
        }
    }

    override fun getNortonResistance(value: Double) = simulation.dt / value

    /**
     * The capacitance of the capacitor.
     * Changing this is expensive!
     * */
    var capacitance: Double
        get() = componentValue
        set(value) { componentValue = value }

    /**
     * Potential across the device from the last timestep.
     * */
    var lastPotential: Double = 0.0

    /**
     * The last potential difference, calculated in [finishStep].
     * */
    var lastDv = 0.0

    /**
     * The amount of charge this capacitor has accumulated.
     */
    var charge: Double = 0.0

    /**
     * Reconciles [charge] and [lastPotential] so we don't get phantom energy input when either is incorrect.
     *
     * Simply put, the capacitor enforces `V = Q / C`.
     * If this state is not consistent, we will get some feedback.
     * */
    private fun sanitizeState() {
        /**
         * Potential across the device expected from the current charge and capacitance:
         * */
        val expectedPotential = charge / capacitance

        /**
         * Error (P.S. at this point, `potential = lastPotential`)
         * */
        val error = expectedPotential - lastPotential

        if (abs(error) <= CONSISTENCY_TOLERANCE) {
            lastDv = error
            lastPotential = expectedPotential
            return
        }

        // Reconcile by preserving charge:
        val v0 = lastPotential
        lastPotential = expectedPotential
        lastDv = lastPotential - v0
    }

    override fun prepareStep() {
        sanitizeState()

        nortonCurrent = charge / simulation.dt
        trickUsed = false
    }

    override fun finishStep() {
        val potential = potential

        val dv = potential - lastPotential
        val dq = capacitance * dv

        charge += dq
        lastPotential = potential
        lastDv = dv
    }

    /**
     * Removes energy from the capacitor.
     * @param requestedEnergy The upper bound on the energy to withdraw.
     * @return The actual energy that was removed.
     *
     * **P.S. If you want to use [lostEnergy], use it before calling this. This affects that result.
     */
    fun withdrawEnergy(requestedEnergy: Double): Double {
        require(requestedEnergy >= 0.0 && !requestedEnergy.isNaN() && !requestedEnergy.isInfinite()) {
            "Invalid requested energy $requestedEnergy!"
        }

        if (requestedEnergy <= 0.0 || capacitance <= 0.0) {
            return 0.0
        }

        val internalEnergy = this@Capacitor.internalEnergy
        val energyToRemove = min(requestedEnergy, internalEnergy)
        val newEnergy = internalEnergy - energyToRemove
        val newCharge = sign(charge) * sqrt(2.0 * capacitance * newEnergy)

        charge = newCharge

        val temp = lastPotential
        lastPotential = newCharge / capacitance
        lastDv = lastPotential - temp

        return energyToRemove
    }

    private var trickUsed = false

    /**
     * Removes energy from the capacitor, but first checks if the numeric losses of the model satisfy this request.
     * If not, it fills the rest of the request with [withdrawEnergy].
     * **Call this once per tick, at most!**
     *
     * Over time, using this instead of [withdrawEnergy] results in a more accurate energy balance.
     * Keep in mind that, if the [lostEnergy] is not wholly consumed this step, it will be gone next step.
     * */
    fun withdrawEnergyTrick(requestedEnergy: Double): Double {
        check(!trickUsed) {
            "Cannot use the energy trick more than once per tick!"
        }

        trickUsed = true

        val loss = lostEnergy

        if(requestedEnergy <= loss) {
            return requestedEnergy
        }

        return loss + withdrawEnergy(requestedEnergy - loss)
    }

    /**
     * Gets the energy stored based on the current [charge].
     * */
    val internalEnergy get() = 0.5 * charge * charge / capacitance

    /**
     * Energy lost in the numerical model this step.
     * */
    val lostEnergy get() = 0.5 * capacitance * (lastDv * lastDv)

    /**
     * Gets the total energy possible to withdraw with [withdrawEnergyTrick].
     * */
    val virtualEnergy get() = this@Capacitor.internalEnergy + lostEnergy

    val power get() = potential * current
}

/**
 * Diode implemented as a potential-controlled switch, at `V = 0`. Uses hysteresis to harden against oscillations.
 * This is the cheapest possible way to implement something **like** a diode.
 * It doesn't simulate a semiconductor so no nonlinear behavior can be extracted from this, to formulate other simulations (e.g. the solar panel simulation).
 * All that must be simulated with a model (for example, a [PotentialSource] in series with a [LinearDiode], where the source potential is modulated).
 * */
class LinearDiode : Resistor() {
    /**
     * If true, the diode is in its conducting state.
     * */
    var isConducting: Boolean

    /**
     * Hysteresis voltage to reduce oscillations.
     * Explanation: The state won't switch if only the potential's sign switched.
     * We check if the potential changed more than [hysteresisVoltage] above or below `0`. Only then, we apply the switch.
     */
    var hysteresisVoltage: Double = 0.01

    /**
     * The resistance in forward bias (that is, when the potential is positive).
     * */
    var forwardResistance: Double = 0.01
        set(value) {
            if (value < ElectricalSimulation.MIN_RESISTANCE || value > ElectricalSimulation.MAX_RESISTANCE || value.isNaN() || value.isInfinite()) {
                error("Invalid forward resistance $value!")
            }

            field = value

            if(isConducting) {
                resistance = value
            }
        }

    /**
     * The resistance in reverse bias (that is, when the potential is negative).
     */
    var reverseResistance: Double = 1000.0
        set(value) {
            if (value < ElectricalSimulation.MIN_RESISTANCE || value > ElectricalSimulation.MAX_RESISTANCE || value.isNaN() || value.isInfinite()) {
                error("Invalid reverse resistance $value!")
            }

            field = value

            if(!isConducting) {
                resistance = value
            }
        }

    /**
     * Sets the diode as initially open.
     * */
    init {
        isConducting = false
        resistance = reverseResistance
    }

    /**
     * Switches the resistance, with hysteresis to make it more resistant to oscillations.
     * */
    override fun prepareStep() {
        val potential = potential

        /**
         * Conductance based on the ideal behavior:
         * */
        val isInPositiveRegion = potential > 0.0

        /**
         * Apply hysteresis:
         * */
        val targetState = if (isInPositiveRegion != isConducting) {
            if (isInPositiveRegion) {
                potential > hysteresisVoltage
            }
            else {
                !(potential < -hysteresisVoltage)
            }
        }
        else {
            // No state change:
            isConducting
        }

        /**
         * Update resistance if needed:
         * */
        if (targetState != isConducting) {
            isConducting = targetState

            resistance = if (targetState) {
                forwardResistance
            }
            else {
                reverseResistance
            }
        }
    }
}

/**
 * Power device implemented as a Norton system.
 * The Norton current is an unknown that is found by a special iterative solver.
 * We have implementations for both generator and load:
 * - [PowerConsumer]
 * - [PowerSource]
 *
 * These are not solved simultaneously. For more information, see the documentation on [ElectricalSimulation].
 * */
abstract class PowerDevice : NortonSystem() {
    /**
     * The stabilizing resistance of the Norton system.
     * The smaller it is, the stiffer the problem.
     * There is a sweet spot. I recommend leaving it set to `1` or `0.1`.
     * If you work with very high potentials, you might want to increase it a little.
     * */
    var characteristicResistance: Double
        get() = componentValue
        set(value) { componentValue = value }
}

/**
 * Nonlinear device solved with successive over-relaxation.
 * */
interface SuccessiveOverRelaxationSolve {

}

/**
 * Grissess-style power-controlled sink, implemented as a Norton system with a constant conductance.
 * Solved using a cheap approximate successive over-relaxation method (see [ElectricalSimulation.PowerConsumerSolver]).
 * ## Recommendations:
 * ### Add a [Capacitor] in parallel:
 * - The capacitor will absorb the shock of a sudden switch
 * - When the consumer suddenly tries to draw a large current, the capacitor will supply it and the circuit potential won't collapse
 * - When the consumer suddenly stops drawing, the capacitor absorbs the potential spike
 * - It smooths the potential coming into the calculation
 * ### Add a [Resistor] in series (with the capacitor-consumer system):
 * - The resistor will further arrest large spikes sent by the stiff device
 * */
class PowerConsumer : PowerDevice(), ReadoutElectricalComponent<PowerConsumer, PowerConsumer.Repository> {
    override val repositoryLayer = ElectricalReadoutRepositoryLayer<Repository> {
        Repository(this)
    }

    class Repository(val consumer: PowerConsumer) : ReadoutRepository {
        var potential = Quantity(0.0, VOLT)
            private set

        var current = Quantity(0.0, AMPERE)
            private set

        var power = Quantity(0.0, WATT)
            private set

        override fun loadValues() {
            potential = Quantity(consumer.potential)
            current = Quantity(consumer.current)
            power = Quantity(consumer.power)
        }
    }

    /**
     * The maximum power to consume.
     * */
    var targetPower: Double = 0.0
        set(value) {
            if (value.isNaN() || value.isInfinite() || value < 0.0) {
                error("Invalid target power $value")
            }

            field = value
        }

    /**
     * The minimum "equivalent resistance" of the device.
     * This is approximately the resistance you'd have to give to a resistor that replaced this device in the circuit and didn't change anything.
     * This constraint ensures we do not create a short-circuit, which is not solvable.
     * */
    var minEquivalentResistance: Double = 1.0
        set(value) {
            if (value.isNaN() || value.isInfinite() || value < ElectricalSimulation.MIN_RESISTANCE || value > ElectricalSimulation.MAX_RESISTANCE) {
                error("Invalid min equivalent resistance $value")
            }

            field = value
        }

    /**
     * The power being consumed. In normal conditions, it is positive.
     * **It can be negative due to solver error. Please ensure you treat that case, possibly by just taking that value as 0.**
     * */
    val power get() = potential * current
}

/**
 * The [PowerSource] is the most complex and powerful generator component in the electrical simulation.
 * Unlike a simple [PotentialSource] or [CurrentSource], it doesn't use a fixed (independent) potential or current.
 * Instead, it attempts to **generate a specific power**, making it an ideal component for modeling advanced, stiff, finely-grained devices like DC-DC converters, that dispatch energy from a small buffer.
 * This precision comes at a cost. The [PowerSource] is a nonlinear component that doesn't fit in the standard MNA formulation, meaning it requires an expensive iterative solver ([ElectricalSimulation.PowerSourceSystem]) to find its operating point at every timestep, in tandem with every other [PowerSource].
 * */
class PowerSource : PowerDevice(), ReadoutElectricalComponent<PowerSource, PowerSource.Repository> {
    override val repositoryLayer = ElectricalReadoutRepositoryLayer<Repository> {
        Repository(this)
    }

    class Repository(val source: PowerSource) : ReadoutRepository {
        var maxPotential = Quantity(0.0, VOLT)
            private set

        var potential = Quantity(0.0, VOLT)
            private set

        var current = Quantity(0.0, AMPERE)
            private set

        var power = Quantity(0.0, WATT)
            private set

        override fun loadValues() {
            maxPotential = Quantity(source.maxPotential)
            potential = Quantity(source.potential)
            current = Quantity(source.current)
            power = Quantity(source.power)
        }
    }

    /**
     * The index of this source into the nonlinear system.
     * */
    var powerSourceIndex = -1
        private set

    /**
     * Sets the device's nonlinear solver index.
     * */
    internal fun setPowerSourceIndex(index: Int) {
        check(powerSourceIndex == -1) {
            "Tried to set power source index, but previous simulation wasn't destroyed!"
        }

        powerSourceIndex = index
    }

    /**
     * Resets the nonlinear solver index.
     * */
    override fun simulationDestroyed() {
        super.simulationDestroyed()

        powerSourceIndex = -1
    }

    /**
     * This is the open-circuit potential of the power source.
     * */
    var maxPotential: Double = 1.0
        set(value) {
            if(value.isNaN() || value.isInfinite() || value < 0.0) {
                error("Invalid max potential $value")
            }

            field = value
        }

    /**
     * Internally, the power term used in the residual starts dropping when [potential] `>` [maxPotential]`×`[blendRegion].
     * */
    var blendRegion: Double = 0.95
        set(value) {
            if(value.isNaN() || value.isInfinite() || value <= 0.0 || value >= 1.0) {
                error("Invalid blend region $value")
            }

            field = value
        }

    /**
     * The (max) power to generate or consume.
     *
     * Based on the potential at the operating point:
     * - If the potential is negative, then the source will simply push all possible power ([power] ≈ [targetPower])
     * - If the potential is positive, then the source will push some fraction of the desired power ([power] ∈ `[0, `[targetPower]`]`)
     * */
    var targetPower: Double = 0.0
        set(value) {
            if(value.isNaN() || value.isInfinite()) {
                error("Invalid target power $value")
            }

            if(value < 0.0) {
                error("Target power must be positive! $value")
            }

            field = value
        }

    /**
     * Gets the power generated by this source. By Grissess' convention, this is positive when power is leaving the source.
     * If it is negative, then it is entering the source.
     *
     * Even if you set this up as a generator or consumer, you may get the opposite sign of the power you expect here.
     * That happens if the circuit is "overpowering" this source (i.e. it is inducing a potential larger than what the source can compensate for with your target power).
     * This is expected behavior. If this is disruptive, consider using a diode. Also consider using that power violation to heat up the device.
     * */
    val power get() = -potential * current
}