# This workflow publishes packages every time we make a GitHub Release.

name: Publish package to GitHub Packages

on:
    release:
        types: [created]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "publish"
    publish:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        -   uses: actions/checkout@v2
        -   uses: actions/setup-java@v1
            with:
                java-version: 17

        -   uses: actions/cache@v1
            with:
                path: ~/.gradle/caches
                key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
                # This allows restoring a *non-matching* cache on a cache miss, and considers it a match even if
                # (anything but) the gradle files have changed. Since it's the gradle cache directory
                # we're restoring, this is still acceptable and potentially useful.
                restore-keys: |
                    ${{ runner.os }}-gradle-

        -   name: Change Gradlew permission
            run: chmod +x ./gradlew

        -   name: Build the project
            run: ./gradlew build

        -   name: Run tests
            run: ./gradlew test
        -   name: Publish package
            run: ./gradlew publish
            env:
                GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
